[font]
size = 11.0

[font.bold]
family = "monospace"

[font.bold_italic]
family = "monospace"

[font.italic]
family = "monospace"

[font.normal]
family = "monospace"
style = "Regular"

[window]
opacity = 0.8
